### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alexanderimanicowenrivers**
Adding in extended installation instructions.

### CODE REVIEW

**Comment by hsezhiyan** [comment]
@alexanderimanicowenrivers can you please add the full tutorial example on here? The reviewer will likely want to see it on the README.md.

**Comment by huangsicong** [comment]
Maybe we should decide where to make and review our PRs? Because I think some changes are made in the private repo and some are made here, which might be confusing or missing bits and pieces in the end. I think one option is to make all PRs in the private codebase, and then after everything is finalized we push all changes to here and update reviewers

**Review by huangsicong — APPROVED** [review]
Looks good to me. Thanks!

**Comment by huangsicong** [comment]
The full tutorial samples is included in the readthedocs. I think we can point the reviewers to readthedocs.

**Pull request merged**
