### PR TITLE
Adding the source code of documentation

### PR DESCRIPTION
**Pull request by huangsicong**
Transferring the source code of documentation from https://github.com/hsezhiyan/forai-rl-docs to here. The online documentation can be found here: https://rl-codebase.readthedocs.io/en/latest/

### CODE REVIEW

**Review by hsezhiyan — CHANGES_REQUESTED** [review]
@huangsicong can you connect the readthedocs `forai-demo` to this location and verify the build works properly? The readthedocs site is currently still built from my repo (I looked at the Github source and it pointed to my repo).

**Comment by huangsicong** [comment]
Yeah sure, I just checked that and it works properly. Please see here: https://forai-demo.readthedocs.io/en/latest/
Thanks!

**Review by bryanlimy — APPROVED** [review]
LGTM

**Review by bryanlimy — APPROVED** [review]
LGTM

**Pull request merged**
